# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robobo_msgs/MoveWheelsRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class MoveWheelsRequest(genpy.Message):
  _md5sum = "e266bff9487ab0f7db9d11321bda62d1"
  _type = "robobo_msgs/MoveWheelsRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """std_msgs/Int8 lspeed
std_msgs/Int8 rspeed
std_msgs/Int32 time
std_msgs/Int16 unlockid

================================================================================
MSG: std_msgs/Int8
int8 data

================================================================================
MSG: std_msgs/Int32
int32 data
================================================================================
MSG: std_msgs/Int16
int16 data
"""
  __slots__ = ['lspeed','rspeed','time','unlockid']
  _slot_types = ['std_msgs/Int8','std_msgs/Int8','std_msgs/Int32','std_msgs/Int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       lspeed,rspeed,time,unlockid

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MoveWheelsRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.lspeed is None:
        self.lspeed = std_msgs.msg.Int8()
      if self.rspeed is None:
        self.rspeed = std_msgs.msg.Int8()
      if self.time is None:
        self.time = std_msgs.msg.Int32()
      if self.unlockid is None:
        self.unlockid = std_msgs.msg.Int16()
    else:
      self.lspeed = std_msgs.msg.Int8()
      self.rspeed = std_msgs.msg.Int8()
      self.time = std_msgs.msg.Int32()
      self.unlockid = std_msgs.msg.Int16()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2bih().pack(_x.lspeed.data, _x.rspeed.data, _x.time.data, _x.unlockid.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.lspeed is None:
        self.lspeed = std_msgs.msg.Int8()
      if self.rspeed is None:
        self.rspeed = std_msgs.msg.Int8()
      if self.time is None:
        self.time = std_msgs.msg.Int32()
      if self.unlockid is None:
        self.unlockid = std_msgs.msg.Int16()
      end = 0
      _x = self
      start = end
      end += 8
      (_x.lspeed.data, _x.rspeed.data, _x.time.data, _x.unlockid.data,) = _get_struct_2bih().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2bih().pack(_x.lspeed.data, _x.rspeed.data, _x.time.data, _x.unlockid.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.lspeed is None:
        self.lspeed = std_msgs.msg.Int8()
      if self.rspeed is None:
        self.rspeed = std_msgs.msg.Int8()
      if self.time is None:
        self.time = std_msgs.msg.Int32()
      if self.unlockid is None:
        self.unlockid = std_msgs.msg.Int16()
      end = 0
      _x = self
      start = end
      end += 8
      (_x.lspeed.data, _x.rspeed.data, _x.time.data, _x.unlockid.data,) = _get_struct_2bih().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2bih = None
def _get_struct_2bih():
    global _struct_2bih
    if _struct_2bih is None:
        _struct_2bih = struct.Struct("<2bih")
    return _struct_2bih
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robobo_msgs/MoveWheelsResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class MoveWheelsResponse(genpy.Message):
  _md5sum = "b41202f44ec8802b6a66ae15859258a4"
  _type = "robobo_msgs/MoveWheelsResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """std_msgs/Int8 error


================================================================================
MSG: std_msgs/Int8
int8 data
"""
  __slots__ = ['error']
  _slot_types = ['std_msgs/Int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       error

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MoveWheelsResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.error is None:
        self.error = std_msgs.msg.Int8()
    else:
      self.error = std_msgs.msg.Int8()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_b().pack(self.error.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.error is None:
        self.error = std_msgs.msg.Int8()
      end = 0
      start = end
      end += 1
      (self.error.data,) = _get_struct_b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_get_struct_b().pack(self.error.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.error is None:
        self.error = std_msgs.msg.Int8()
      end = 0
      start = end
      end += 1
      (self.error.data,) = _get_struct_b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_b = None
def _get_struct_b():
    global _struct_b
    if _struct_b is None:
        _struct_b = struct.Struct("<b")
    return _struct_b
class MoveWheels(object):
  _type          = 'robobo_msgs/MoveWheels'
  _md5sum = 'f7d9b6ab6c37c283e7f3f620a3f5c819'
  _request_class  = MoveWheelsRequest
  _response_class = MoveWheelsResponse
