// Generated by gencpp from file robobo_msgs/IRs.msg
// DO NOT EDIT!


#ifndef ROBOBO_MSGS_MESSAGE_IRS_H
#define ROBOBO_MSGS_MESSAGE_IRS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Range.h>
#include <sensor_msgs/Range.h>
#include <sensor_msgs/Range.h>
#include <sensor_msgs/Range.h>
#include <sensor_msgs/Range.h>
#include <sensor_msgs/Range.h>
#include <sensor_msgs/Range.h>
#include <sensor_msgs/Range.h>

namespace robobo_msgs
{
template <class ContainerAllocator>
struct IRs_
{
  typedef IRs_<ContainerAllocator> Type;

  IRs_()
    : FrontC()
    , FrontR()
    , FrontRR()
    , FrontL()
    , FrontLL()
    , BackC()
    , BackR()
    , BackL()  {
    }
  IRs_(const ContainerAllocator& _alloc)
    : FrontC(_alloc)
    , FrontR(_alloc)
    , FrontRR(_alloc)
    , FrontL(_alloc)
    , FrontLL(_alloc)
    , BackC(_alloc)
    , BackR(_alloc)
    , BackL(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Range_<ContainerAllocator>  _FrontC_type;
  _FrontC_type FrontC;

   typedef  ::sensor_msgs::Range_<ContainerAllocator>  _FrontR_type;
  _FrontR_type FrontR;

   typedef  ::sensor_msgs::Range_<ContainerAllocator>  _FrontRR_type;
  _FrontRR_type FrontRR;

   typedef  ::sensor_msgs::Range_<ContainerAllocator>  _FrontL_type;
  _FrontL_type FrontL;

   typedef  ::sensor_msgs::Range_<ContainerAllocator>  _FrontLL_type;
  _FrontLL_type FrontLL;

   typedef  ::sensor_msgs::Range_<ContainerAllocator>  _BackC_type;
  _BackC_type BackC;

   typedef  ::sensor_msgs::Range_<ContainerAllocator>  _BackR_type;
  _BackR_type BackR;

   typedef  ::sensor_msgs::Range_<ContainerAllocator>  _BackL_type;
  _BackL_type BackL;





  typedef boost::shared_ptr< ::robobo_msgs::IRs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robobo_msgs::IRs_<ContainerAllocator> const> ConstPtr;

}; // struct IRs_

typedef ::robobo_msgs::IRs_<std::allocator<void> > IRs;

typedef boost::shared_ptr< ::robobo_msgs::IRs > IRsPtr;
typedef boost::shared_ptr< ::robobo_msgs::IRs const> IRsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robobo_msgs::IRs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robobo_msgs::IRs_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robobo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'robobo_msgs': ['/root/projects/src/robobo_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robobo_msgs::IRs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robobo_msgs::IRs_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robobo_msgs::IRs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robobo_msgs::IRs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robobo_msgs::IRs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robobo_msgs::IRs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robobo_msgs::IRs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3cda0da1598fe1278d12814909cfb3d7";
  }

  static const char* value(const ::robobo_msgs::IRs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3cda0da1598fe127ULL;
  static const uint64_t static_value2 = 0x8d12814909cfb3d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::robobo_msgs::IRs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robobo_msgs/IRs";
  }

  static const char* value(const ::robobo_msgs::IRs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robobo_msgs::IRs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Range FrontC\n\
sensor_msgs/Range FrontR\n\
sensor_msgs/Range FrontRR\n\
sensor_msgs/Range FrontL\n\
sensor_msgs/Range FrontLL\n\
sensor_msgs/Range BackC\n\
sensor_msgs/Range BackR\n\
sensor_msgs/Range BackL\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Range\n\
# Single range reading from an active ranger that emits energy and reports\n\
# one range reading that is valid along an arc at the distance measured. \n\
# This message is  not appropriate for laser scanners. See the LaserScan\n\
# message if you are working with a laser scanner.\n\
\n\
# This message also can represent a fixed-distance (binary) ranger.  This\n\
# sensor will have min_range===max_range===distance of detection.\n\
# These sensors follow REP 117 and will output -Inf if the object is detected\n\
# and +Inf if the object is outside of the detection range.\n\
\n\
Header header           # timestamp in the header is the time the ranger\n\
                        # returned the distance reading\n\
\n\
# Radiation type enums\n\
# If you want a value added to this list, send an email to the ros-users list\n\
uint8 ULTRASOUND=0\n\
uint8 INFRARED=1\n\
\n\
uint8 radiation_type    # the type of radiation used by the sensor\n\
                        # (sound, IR, etc) [enum]\n\
\n\
float32 field_of_view   # the size of the arc that the distance reading is\n\
                        # valid for [rad]\n\
                        # the object causing the range reading may have\n\
                        # been anywhere within -field_of_view/2 and\n\
                        # field_of_view/2 at the measured range. \n\
                        # 0 angle corresponds to the x-axis of the sensor.\n\
\n\
float32 min_range       # minimum range value [m]\n\
float32 max_range       # maximum range value [m]\n\
                        # Fixed distance rangers require min_range==max_range\n\
\n\
float32 range           # range data [m]\n\
                        # (Note: values < range_min or > range_max\n\
                        # should be discarded)\n\
                        # Fixed distance rangers only output -Inf or +Inf.\n\
                        # -Inf represents a detection within fixed distance.\n\
                        # (Detection too close to the sensor to quantify)\n\
                        # +Inf represents no detection within the fixed distance.\n\
                        # (Object out of range)\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::robobo_msgs::IRs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robobo_msgs::IRs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.FrontC);
      stream.next(m.FrontR);
      stream.next(m.FrontRR);
      stream.next(m.FrontL);
      stream.next(m.FrontLL);
      stream.next(m.BackC);
      stream.next(m.BackR);
      stream.next(m.BackL);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IRs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robobo_msgs::IRs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robobo_msgs::IRs_<ContainerAllocator>& v)
  {
    s << indent << "FrontC: ";
    s << std::endl;
    Printer< ::sensor_msgs::Range_<ContainerAllocator> >::stream(s, indent + "  ", v.FrontC);
    s << indent << "FrontR: ";
    s << std::endl;
    Printer< ::sensor_msgs::Range_<ContainerAllocator> >::stream(s, indent + "  ", v.FrontR);
    s << indent << "FrontRR: ";
    s << std::endl;
    Printer< ::sensor_msgs::Range_<ContainerAllocator> >::stream(s, indent + "  ", v.FrontRR);
    s << indent << "FrontL: ";
    s << std::endl;
    Printer< ::sensor_msgs::Range_<ContainerAllocator> >::stream(s, indent + "  ", v.FrontL);
    s << indent << "FrontLL: ";
    s << std::endl;
    Printer< ::sensor_msgs::Range_<ContainerAllocator> >::stream(s, indent + "  ", v.FrontLL);
    s << indent << "BackC: ";
    s << std::endl;
    Printer< ::sensor_msgs::Range_<ContainerAllocator> >::stream(s, indent + "  ", v.BackC);
    s << indent << "BackR: ";
    s << std::endl;
    Printer< ::sensor_msgs::Range_<ContainerAllocator> >::stream(s, indent + "  ", v.BackR);
    s << indent << "BackL: ";
    s << std::endl;
    Printer< ::sensor_msgs::Range_<ContainerAllocator> >::stream(s, indent + "  ", v.BackL);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOBO_MSGS_MESSAGE_IRS_H
