// Generated by gencpp from file robobo_msgs/MovePanTilt.msg
// DO NOT EDIT!


#ifndef ROBOBO_MSGS_MESSAGE_MOVEPANTILT_H
#define ROBOBO_MSGS_MESSAGE_MOVEPANTILT_H

#include <ros/service_traits.h>


#include <robobo_msgs/MovePanTiltRequest.h>
#include <robobo_msgs/MovePanTiltResponse.h>


namespace robobo_msgs
{

struct MovePanTilt
{

typedef MovePanTiltRequest Request;
typedef MovePanTiltResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MovePanTilt
} // namespace robobo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robobo_msgs::MovePanTilt > {
  static const char* value()
  {
    return "cf92955e4ca6d280225977f6e00d71c8";
  }

  static const char* value(const ::robobo_msgs::MovePanTilt&) { return value(); }
};

template<>
struct DataType< ::robobo_msgs::MovePanTilt > {
  static const char* value()
  {
    return "robobo_msgs/MovePanTilt";
  }

  static const char* value(const ::robobo_msgs::MovePanTilt&) { return value(); }
};


// service_traits::MD5Sum< ::robobo_msgs::MovePanTiltRequest> should match 
// service_traits::MD5Sum< ::robobo_msgs::MovePanTilt > 
template<>
struct MD5Sum< ::robobo_msgs::MovePanTiltRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robobo_msgs::MovePanTilt >::value();
  }
  static const char* value(const ::robobo_msgs::MovePanTiltRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robobo_msgs::MovePanTiltRequest> should match 
// service_traits::DataType< ::robobo_msgs::MovePanTilt > 
template<>
struct DataType< ::robobo_msgs::MovePanTiltRequest>
{
  static const char* value()
  {
    return DataType< ::robobo_msgs::MovePanTilt >::value();
  }
  static const char* value(const ::robobo_msgs::MovePanTiltRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robobo_msgs::MovePanTiltResponse> should match 
// service_traits::MD5Sum< ::robobo_msgs::MovePanTilt > 
template<>
struct MD5Sum< ::robobo_msgs::MovePanTiltResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robobo_msgs::MovePanTilt >::value();
  }
  static const char* value(const ::robobo_msgs::MovePanTiltResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robobo_msgs::MovePanTiltResponse> should match 
// service_traits::DataType< ::robobo_msgs::MovePanTilt > 
template<>
struct DataType< ::robobo_msgs::MovePanTiltResponse>
{
  static const char* value()
  {
    return DataType< ::robobo_msgs::MovePanTilt >::value();
  }
  static const char* value(const ::robobo_msgs::MovePanTiltResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOBO_MSGS_MESSAGE_MOVEPANTILT_H
