// Generated by gencpp from file robobo_msgs/SetCamera.msg
// DO NOT EDIT!


#ifndef ROBOBO_MSGS_MESSAGE_SETCAMERA_H
#define ROBOBO_MSGS_MESSAGE_SETCAMERA_H

#include <ros/service_traits.h>


#include <robobo_msgs/SetCameraRequest.h>
#include <robobo_msgs/SetCameraResponse.h>


namespace robobo_msgs
{

struct SetCamera
{

typedef SetCameraRequest Request;
typedef SetCameraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCamera
} // namespace robobo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robobo_msgs::SetCamera > {
  static const char* value()
  {
    return "90a7c1d0dd1fb7ca39545c447b7dd045";
  }

  static const char* value(const ::robobo_msgs::SetCamera&) { return value(); }
};

template<>
struct DataType< ::robobo_msgs::SetCamera > {
  static const char* value()
  {
    return "robobo_msgs/SetCamera";
  }

  static const char* value(const ::robobo_msgs::SetCamera&) { return value(); }
};


// service_traits::MD5Sum< ::robobo_msgs::SetCameraRequest> should match 
// service_traits::MD5Sum< ::robobo_msgs::SetCamera > 
template<>
struct MD5Sum< ::robobo_msgs::SetCameraRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robobo_msgs::SetCamera >::value();
  }
  static const char* value(const ::robobo_msgs::SetCameraRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robobo_msgs::SetCameraRequest> should match 
// service_traits::DataType< ::robobo_msgs::SetCamera > 
template<>
struct DataType< ::robobo_msgs::SetCameraRequest>
{
  static const char* value()
  {
    return DataType< ::robobo_msgs::SetCamera >::value();
  }
  static const char* value(const ::robobo_msgs::SetCameraRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robobo_msgs::SetCameraResponse> should match 
// service_traits::MD5Sum< ::robobo_msgs::SetCamera > 
template<>
struct MD5Sum< ::robobo_msgs::SetCameraResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robobo_msgs::SetCamera >::value();
  }
  static const char* value(const ::robobo_msgs::SetCameraResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robobo_msgs::SetCameraResponse> should match 
// service_traits::DataType< ::robobo_msgs::SetCamera > 
template<>
struct DataType< ::robobo_msgs::SetCameraResponse>
{
  static const char* value()
  {
    return DataType< ::robobo_msgs::SetCamera >::value();
  }
  static const char* value(const ::robobo_msgs::SetCameraResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOBO_MSGS_MESSAGE_SETCAMERA_H
