// Generated by gencpp from file robobo_msgs/SetEmotionRequest.msg
// DO NOT EDIT!


#ifndef ROBOBO_MSGS_MESSAGE_SETEMOTIONREQUEST_H
#define ROBOBO_MSGS_MESSAGE_SETEMOTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace robobo_msgs
{
template <class ContainerAllocator>
struct SetEmotionRequest_
{
  typedef SetEmotionRequest_<ContainerAllocator> Type;

  SetEmotionRequest_()
    : emotion()  {
    }
  SetEmotionRequest_(const ContainerAllocator& _alloc)
    : emotion(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _emotion_type;
  _emotion_type emotion;





  typedef boost::shared_ptr< ::robobo_msgs::SetEmotionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robobo_msgs::SetEmotionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetEmotionRequest_

typedef ::robobo_msgs::SetEmotionRequest_<std::allocator<void> > SetEmotionRequest;

typedef boost::shared_ptr< ::robobo_msgs::SetEmotionRequest > SetEmotionRequestPtr;
typedef boost::shared_ptr< ::robobo_msgs::SetEmotionRequest const> SetEmotionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robobo_msgs::SetEmotionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robobo_msgs::SetEmotionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robobo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'robobo_msgs': ['/root/projects/src/robobo_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robobo_msgs::SetEmotionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robobo_msgs::SetEmotionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robobo_msgs::SetEmotionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robobo_msgs::SetEmotionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robobo_msgs::SetEmotionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robobo_msgs::SetEmotionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robobo_msgs::SetEmotionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a6515dd33a2228f41cfa2f673f8eb2aa";
  }

  static const char* value(const ::robobo_msgs::SetEmotionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa6515dd33a2228f4ULL;
  static const uint64_t static_value2 = 0x1cfa2f673f8eb2aaULL;
};

template<class ContainerAllocator>
struct DataType< ::robobo_msgs::SetEmotionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robobo_msgs/SetEmotionRequest";
  }

  static const char* value(const ::robobo_msgs::SetEmotionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robobo_msgs::SetEmotionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String emotion\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::robobo_msgs::SetEmotionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robobo_msgs::SetEmotionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.emotion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetEmotionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robobo_msgs::SetEmotionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robobo_msgs::SetEmotionRequest_<ContainerAllocator>& v)
  {
    s << indent << "emotion: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.emotion);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOBO_MSGS_MESSAGE_SETEMOTIONREQUEST_H
