# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robobo_msgs/IRs.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg
import sensor_msgs.msg

class IRs(genpy.Message):
  _md5sum = "3cda0da1598fe1278d12814909cfb3d7"
  _type = "robobo_msgs/IRs"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """sensor_msgs/Range FrontC
sensor_msgs/Range FrontR
sensor_msgs/Range FrontRR
sensor_msgs/Range FrontL
sensor_msgs/Range FrontLL
sensor_msgs/Range BackC
sensor_msgs/Range BackR
sensor_msgs/Range BackL

================================================================================
MSG: sensor_msgs/Range
# Single range reading from an active ranger that emits energy and reports
# one range reading that is valid along an arc at the distance measured. 
# This message is  not appropriate for laser scanners. See the LaserScan
# message if you are working with a laser scanner.

# This message also can represent a fixed-distance (binary) ranger.  This
# sensor will have min_range===max_range===distance of detection.
# These sensors follow REP 117 and will output -Inf if the object is detected
# and +Inf if the object is outside of the detection range.

Header header           # timestamp in the header is the time the ranger
                        # returned the distance reading

# Radiation type enums
# If you want a value added to this list, send an email to the ros-users list
uint8 ULTRASOUND=0
uint8 INFRARED=1

uint8 radiation_type    # the type of radiation used by the sensor
                        # (sound, IR, etc) [enum]

float32 field_of_view   # the size of the arc that the distance reading is
                        # valid for [rad]
                        # the object causing the range reading may have
                        # been anywhere within -field_of_view/2 and
                        # field_of_view/2 at the measured range. 
                        # 0 angle corresponds to the x-axis of the sensor.

float32 min_range       # minimum range value [m]
float32 max_range       # maximum range value [m]
                        # Fixed distance rangers require min_range==max_range

float32 range           # range data [m]
                        # (Note: values < range_min or > range_max
                        # should be discarded)
                        # Fixed distance rangers only output -Inf or +Inf.
                        # -Inf represents a detection within fixed distance.
                        # (Detection too close to the sensor to quantify)
                        # +Inf represents no detection within the fixed distance.
                        # (Object out of range)
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['FrontC','FrontR','FrontRR','FrontL','FrontLL','BackC','BackR','BackL']
  _slot_types = ['sensor_msgs/Range','sensor_msgs/Range','sensor_msgs/Range','sensor_msgs/Range','sensor_msgs/Range','sensor_msgs/Range','sensor_msgs/Range','sensor_msgs/Range']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       FrontC,FrontR,FrontRR,FrontL,FrontLL,BackC,BackR,BackL

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(IRs, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.FrontC is None:
        self.FrontC = sensor_msgs.msg.Range()
      if self.FrontR is None:
        self.FrontR = sensor_msgs.msg.Range()
      if self.FrontRR is None:
        self.FrontRR = sensor_msgs.msg.Range()
      if self.FrontL is None:
        self.FrontL = sensor_msgs.msg.Range()
      if self.FrontLL is None:
        self.FrontLL = sensor_msgs.msg.Range()
      if self.BackC is None:
        self.BackC = sensor_msgs.msg.Range()
      if self.BackR is None:
        self.BackR = sensor_msgs.msg.Range()
      if self.BackL is None:
        self.BackL = sensor_msgs.msg.Range()
    else:
      self.FrontC = sensor_msgs.msg.Range()
      self.FrontR = sensor_msgs.msg.Range()
      self.FrontRR = sensor_msgs.msg.Range()
      self.FrontL = sensor_msgs.msg.Range()
      self.FrontLL = sensor_msgs.msg.Range()
      self.BackC = sensor_msgs.msg.Range()
      self.BackR = sensor_msgs.msg.Range()
      self.BackL = sensor_msgs.msg.Range()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.FrontC.header.seq, _x.FrontC.header.stamp.secs, _x.FrontC.header.stamp.nsecs))
      _x = self.FrontC.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_B4f3I().pack(_x.FrontC.radiation_type, _x.FrontC.field_of_view, _x.FrontC.min_range, _x.FrontC.max_range, _x.FrontC.range, _x.FrontR.header.seq, _x.FrontR.header.stamp.secs, _x.FrontR.header.stamp.nsecs))
      _x = self.FrontR.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_B4f3I().pack(_x.FrontR.radiation_type, _x.FrontR.field_of_view, _x.FrontR.min_range, _x.FrontR.max_range, _x.FrontR.range, _x.FrontRR.header.seq, _x.FrontRR.header.stamp.secs, _x.FrontRR.header.stamp.nsecs))
      _x = self.FrontRR.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_B4f3I().pack(_x.FrontRR.radiation_type, _x.FrontRR.field_of_view, _x.FrontRR.min_range, _x.FrontRR.max_range, _x.FrontRR.range, _x.FrontL.header.seq, _x.FrontL.header.stamp.secs, _x.FrontL.header.stamp.nsecs))
      _x = self.FrontL.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_B4f3I().pack(_x.FrontL.radiation_type, _x.FrontL.field_of_view, _x.FrontL.min_range, _x.FrontL.max_range, _x.FrontL.range, _x.FrontLL.header.seq, _x.FrontLL.header.stamp.secs, _x.FrontLL.header.stamp.nsecs))
      _x = self.FrontLL.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_B4f3I().pack(_x.FrontLL.radiation_type, _x.FrontLL.field_of_view, _x.FrontLL.min_range, _x.FrontLL.max_range, _x.FrontLL.range, _x.BackC.header.seq, _x.BackC.header.stamp.secs, _x.BackC.header.stamp.nsecs))
      _x = self.BackC.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_B4f3I().pack(_x.BackC.radiation_type, _x.BackC.field_of_view, _x.BackC.min_range, _x.BackC.max_range, _x.BackC.range, _x.BackR.header.seq, _x.BackR.header.stamp.secs, _x.BackR.header.stamp.nsecs))
      _x = self.BackR.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_B4f3I().pack(_x.BackR.radiation_type, _x.BackR.field_of_view, _x.BackR.min_range, _x.BackR.max_range, _x.BackR.range, _x.BackL.header.seq, _x.BackL.header.stamp.secs, _x.BackL.header.stamp.nsecs))
      _x = self.BackL.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_B4f().pack(_x.BackL.radiation_type, _x.BackL.field_of_view, _x.BackL.min_range, _x.BackL.max_range, _x.BackL.range))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.FrontC is None:
        self.FrontC = sensor_msgs.msg.Range()
      if self.FrontR is None:
        self.FrontR = sensor_msgs.msg.Range()
      if self.FrontRR is None:
        self.FrontRR = sensor_msgs.msg.Range()
      if self.FrontL is None:
        self.FrontL = sensor_msgs.msg.Range()
      if self.FrontLL is None:
        self.FrontLL = sensor_msgs.msg.Range()
      if self.BackC is None:
        self.BackC = sensor_msgs.msg.Range()
      if self.BackR is None:
        self.BackR = sensor_msgs.msg.Range()
      if self.BackL is None:
        self.BackL = sensor_msgs.msg.Range()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.FrontC.header.seq, _x.FrontC.header.stamp.secs, _x.FrontC.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.FrontC.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.FrontC.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 29
      (_x.FrontC.radiation_type, _x.FrontC.field_of_view, _x.FrontC.min_range, _x.FrontC.max_range, _x.FrontC.range, _x.FrontR.header.seq, _x.FrontR.header.stamp.secs, _x.FrontR.header.stamp.nsecs,) = _get_struct_B4f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.FrontR.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.FrontR.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 29
      (_x.FrontR.radiation_type, _x.FrontR.field_of_view, _x.FrontR.min_range, _x.FrontR.max_range, _x.FrontR.range, _x.FrontRR.header.seq, _x.FrontRR.header.stamp.secs, _x.FrontRR.header.stamp.nsecs,) = _get_struct_B4f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.FrontRR.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.FrontRR.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 29
      (_x.FrontRR.radiation_type, _x.FrontRR.field_of_view, _x.FrontRR.min_range, _x.FrontRR.max_range, _x.FrontRR.range, _x.FrontL.header.seq, _x.FrontL.header.stamp.secs, _x.FrontL.header.stamp.nsecs,) = _get_struct_B4f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.FrontL.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.FrontL.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 29
      (_x.FrontL.radiation_type, _x.FrontL.field_of_view, _x.FrontL.min_range, _x.FrontL.max_range, _x.FrontL.range, _x.FrontLL.header.seq, _x.FrontLL.header.stamp.secs, _x.FrontLL.header.stamp.nsecs,) = _get_struct_B4f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.FrontLL.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.FrontLL.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 29
      (_x.FrontLL.radiation_type, _x.FrontLL.field_of_view, _x.FrontLL.min_range, _x.FrontLL.max_range, _x.FrontLL.range, _x.BackC.header.seq, _x.BackC.header.stamp.secs, _x.BackC.header.stamp.nsecs,) = _get_struct_B4f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.BackC.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.BackC.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 29
      (_x.BackC.radiation_type, _x.BackC.field_of_view, _x.BackC.min_range, _x.BackC.max_range, _x.BackC.range, _x.BackR.header.seq, _x.BackR.header.stamp.secs, _x.BackR.header.stamp.nsecs,) = _get_struct_B4f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.BackR.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.BackR.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 29
      (_x.BackR.radiation_type, _x.BackR.field_of_view, _x.BackR.min_range, _x.BackR.max_range, _x.BackR.range, _x.BackL.header.seq, _x.BackL.header.stamp.secs, _x.BackL.header.stamp.nsecs,) = _get_struct_B4f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.BackL.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.BackL.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 17
      (_x.BackL.radiation_type, _x.BackL.field_of_view, _x.BackL.min_range, _x.BackL.max_range, _x.BackL.range,) = _get_struct_B4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.FrontC.header.seq, _x.FrontC.header.stamp.secs, _x.FrontC.header.stamp.nsecs))
      _x = self.FrontC.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_B4f3I().pack(_x.FrontC.radiation_type, _x.FrontC.field_of_view, _x.FrontC.min_range, _x.FrontC.max_range, _x.FrontC.range, _x.FrontR.header.seq, _x.FrontR.header.stamp.secs, _x.FrontR.header.stamp.nsecs))
      _x = self.FrontR.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_B4f3I().pack(_x.FrontR.radiation_type, _x.FrontR.field_of_view, _x.FrontR.min_range, _x.FrontR.max_range, _x.FrontR.range, _x.FrontRR.header.seq, _x.FrontRR.header.stamp.secs, _x.FrontRR.header.stamp.nsecs))
      _x = self.FrontRR.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_B4f3I().pack(_x.FrontRR.radiation_type, _x.FrontRR.field_of_view, _x.FrontRR.min_range, _x.FrontRR.max_range, _x.FrontRR.range, _x.FrontL.header.seq, _x.FrontL.header.stamp.secs, _x.FrontL.header.stamp.nsecs))
      _x = self.FrontL.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_B4f3I().pack(_x.FrontL.radiation_type, _x.FrontL.field_of_view, _x.FrontL.min_range, _x.FrontL.max_range, _x.FrontL.range, _x.FrontLL.header.seq, _x.FrontLL.header.stamp.secs, _x.FrontLL.header.stamp.nsecs))
      _x = self.FrontLL.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_B4f3I().pack(_x.FrontLL.radiation_type, _x.FrontLL.field_of_view, _x.FrontLL.min_range, _x.FrontLL.max_range, _x.FrontLL.range, _x.BackC.header.seq, _x.BackC.header.stamp.secs, _x.BackC.header.stamp.nsecs))
      _x = self.BackC.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_B4f3I().pack(_x.BackC.radiation_type, _x.BackC.field_of_view, _x.BackC.min_range, _x.BackC.max_range, _x.BackC.range, _x.BackR.header.seq, _x.BackR.header.stamp.secs, _x.BackR.header.stamp.nsecs))
      _x = self.BackR.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_B4f3I().pack(_x.BackR.radiation_type, _x.BackR.field_of_view, _x.BackR.min_range, _x.BackR.max_range, _x.BackR.range, _x.BackL.header.seq, _x.BackL.header.stamp.secs, _x.BackL.header.stamp.nsecs))
      _x = self.BackL.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_B4f().pack(_x.BackL.radiation_type, _x.BackL.field_of_view, _x.BackL.min_range, _x.BackL.max_range, _x.BackL.range))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.FrontC is None:
        self.FrontC = sensor_msgs.msg.Range()
      if self.FrontR is None:
        self.FrontR = sensor_msgs.msg.Range()
      if self.FrontRR is None:
        self.FrontRR = sensor_msgs.msg.Range()
      if self.FrontL is None:
        self.FrontL = sensor_msgs.msg.Range()
      if self.FrontLL is None:
        self.FrontLL = sensor_msgs.msg.Range()
      if self.BackC is None:
        self.BackC = sensor_msgs.msg.Range()
      if self.BackR is None:
        self.BackR = sensor_msgs.msg.Range()
      if self.BackL is None:
        self.BackL = sensor_msgs.msg.Range()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.FrontC.header.seq, _x.FrontC.header.stamp.secs, _x.FrontC.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.FrontC.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.FrontC.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 29
      (_x.FrontC.radiation_type, _x.FrontC.field_of_view, _x.FrontC.min_range, _x.FrontC.max_range, _x.FrontC.range, _x.FrontR.header.seq, _x.FrontR.header.stamp.secs, _x.FrontR.header.stamp.nsecs,) = _get_struct_B4f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.FrontR.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.FrontR.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 29
      (_x.FrontR.radiation_type, _x.FrontR.field_of_view, _x.FrontR.min_range, _x.FrontR.max_range, _x.FrontR.range, _x.FrontRR.header.seq, _x.FrontRR.header.stamp.secs, _x.FrontRR.header.stamp.nsecs,) = _get_struct_B4f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.FrontRR.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.FrontRR.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 29
      (_x.FrontRR.radiation_type, _x.FrontRR.field_of_view, _x.FrontRR.min_range, _x.FrontRR.max_range, _x.FrontRR.range, _x.FrontL.header.seq, _x.FrontL.header.stamp.secs, _x.FrontL.header.stamp.nsecs,) = _get_struct_B4f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.FrontL.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.FrontL.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 29
      (_x.FrontL.radiation_type, _x.FrontL.field_of_view, _x.FrontL.min_range, _x.FrontL.max_range, _x.FrontL.range, _x.FrontLL.header.seq, _x.FrontLL.header.stamp.secs, _x.FrontLL.header.stamp.nsecs,) = _get_struct_B4f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.FrontLL.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.FrontLL.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 29
      (_x.FrontLL.radiation_type, _x.FrontLL.field_of_view, _x.FrontLL.min_range, _x.FrontLL.max_range, _x.FrontLL.range, _x.BackC.header.seq, _x.BackC.header.stamp.secs, _x.BackC.header.stamp.nsecs,) = _get_struct_B4f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.BackC.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.BackC.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 29
      (_x.BackC.radiation_type, _x.BackC.field_of_view, _x.BackC.min_range, _x.BackC.max_range, _x.BackC.range, _x.BackR.header.seq, _x.BackR.header.stamp.secs, _x.BackR.header.stamp.nsecs,) = _get_struct_B4f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.BackR.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.BackR.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 29
      (_x.BackR.radiation_type, _x.BackR.field_of_view, _x.BackR.min_range, _x.BackR.max_range, _x.BackR.range, _x.BackL.header.seq, _x.BackL.header.stamp.secs, _x.BackL.header.stamp.nsecs,) = _get_struct_B4f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.BackL.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.BackL.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 17
      (_x.BackL.radiation_type, _x.BackL.field_of_view, _x.BackL.min_range, _x.BackL.max_range, _x.BackL.range,) = _get_struct_B4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B4f = None
def _get_struct_B4f():
    global _struct_B4f
    if _struct_B4f is None:
        _struct_B4f = struct.Struct("<B4f")
    return _struct_B4f
_struct_B4f3I = None
def _get_struct_B4f3I():
    global _struct_B4f3I
    if _struct_B4f3I is None:
        _struct_B4f3I = struct.Struct("<B4f3I")
    return _struct_B4f3I
