# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robobo_msgs/Fling.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Fling(genpy.Message):
  _md5sum = "223606e2db34b4f54252a5c13a50f185"
  _type = "robobo_msgs/Fling"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """std_msgs/Int16 angle
std_msgs/Int32 time
std_msgs/Int16 distance

================================================================================
MSG: std_msgs/Int16
int16 data

================================================================================
MSG: std_msgs/Int32
int32 data"""
  __slots__ = ['angle','time','distance']
  _slot_types = ['std_msgs/Int16','std_msgs/Int32','std_msgs/Int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       angle,time,distance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Fling, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.angle is None:
        self.angle = std_msgs.msg.Int16()
      if self.time is None:
        self.time = std_msgs.msg.Int32()
      if self.distance is None:
        self.distance = std_msgs.msg.Int16()
    else:
      self.angle = std_msgs.msg.Int16()
      self.time = std_msgs.msg.Int32()
      self.distance = std_msgs.msg.Int16()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_hih().pack(_x.angle.data, _x.time.data, _x.distance.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.angle is None:
        self.angle = std_msgs.msg.Int16()
      if self.time is None:
        self.time = std_msgs.msg.Int32()
      if self.distance is None:
        self.distance = std_msgs.msg.Int16()
      end = 0
      _x = self
      start = end
      end += 8
      (_x.angle.data, _x.time.data, _x.distance.data,) = _get_struct_hih().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_hih().pack(_x.angle.data, _x.time.data, _x.distance.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.angle is None:
        self.angle = std_msgs.msg.Int16()
      if self.time is None:
        self.time = std_msgs.msg.Int32()
      if self.distance is None:
        self.distance = std_msgs.msg.Int16()
      end = 0
      _x = self
      start = end
      end += 8
      (_x.angle.data, _x.time.data, _x.distance.data,) = _get_struct_hih().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_hih = None
def _get_struct_hih():
    global _struct_hih
    if _struct_hih is None:
        _struct_hih = struct.Struct("<hih")
    return _struct_hih
