// Generated by gencpp from file robobo_msgs/MoveWheels.msg
// DO NOT EDIT!


#ifndef ROBOBO_MSGS_MESSAGE_MOVEWHEELS_H
#define ROBOBO_MSGS_MESSAGE_MOVEWHEELS_H

#include <ros/service_traits.h>


#include <robobo_msgs/MoveWheelsRequest.h>
#include <robobo_msgs/MoveWheelsResponse.h>


namespace robobo_msgs
{

struct MoveWheels
{

typedef MoveWheelsRequest Request;
typedef MoveWheelsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveWheels
} // namespace robobo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robobo_msgs::MoveWheels > {
  static const char* value()
  {
    return "f7d9b6ab6c37c283e7f3f620a3f5c819";
  }

  static const char* value(const ::robobo_msgs::MoveWheels&) { return value(); }
};

template<>
struct DataType< ::robobo_msgs::MoveWheels > {
  static const char* value()
  {
    return "robobo_msgs/MoveWheels";
  }

  static const char* value(const ::robobo_msgs::MoveWheels&) { return value(); }
};


// service_traits::MD5Sum< ::robobo_msgs::MoveWheelsRequest> should match 
// service_traits::MD5Sum< ::robobo_msgs::MoveWheels > 
template<>
struct MD5Sum< ::robobo_msgs::MoveWheelsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robobo_msgs::MoveWheels >::value();
  }
  static const char* value(const ::robobo_msgs::MoveWheelsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robobo_msgs::MoveWheelsRequest> should match 
// service_traits::DataType< ::robobo_msgs::MoveWheels > 
template<>
struct DataType< ::robobo_msgs::MoveWheelsRequest>
{
  static const char* value()
  {
    return DataType< ::robobo_msgs::MoveWheels >::value();
  }
  static const char* value(const ::robobo_msgs::MoveWheelsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robobo_msgs::MoveWheelsResponse> should match 
// service_traits::MD5Sum< ::robobo_msgs::MoveWheels > 
template<>
struct MD5Sum< ::robobo_msgs::MoveWheelsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robobo_msgs::MoveWheels >::value();
  }
  static const char* value(const ::robobo_msgs::MoveWheelsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robobo_msgs::MoveWheelsResponse> should match 
// service_traits::DataType< ::robobo_msgs::MoveWheels > 
template<>
struct DataType< ::robobo_msgs::MoveWheelsResponse>
{
  static const char* value()
  {
    return DataType< ::robobo_msgs::MoveWheels >::value();
  }
  static const char* value(const ::robobo_msgs::MoveWheelsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOBO_MSGS_MESSAGE_MOVEWHEELS_H
