// Generated by gencpp from file robobo_msgs/PlaySound.msg
// DO NOT EDIT!


#ifndef ROBOBO_MSGS_MESSAGE_PLAYSOUND_H
#define ROBOBO_MSGS_MESSAGE_PLAYSOUND_H

#include <ros/service_traits.h>


#include <robobo_msgs/PlaySoundRequest.h>
#include <robobo_msgs/PlaySoundResponse.h>


namespace robobo_msgs
{

struct PlaySound
{

typedef PlaySoundRequest Request;
typedef PlaySoundResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlaySound
} // namespace robobo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robobo_msgs::PlaySound > {
  static const char* value()
  {
    return "c95eacdcbf61c615623911c64d3b591f";
  }

  static const char* value(const ::robobo_msgs::PlaySound&) { return value(); }
};

template<>
struct DataType< ::robobo_msgs::PlaySound > {
  static const char* value()
  {
    return "robobo_msgs/PlaySound";
  }

  static const char* value(const ::robobo_msgs::PlaySound&) { return value(); }
};


// service_traits::MD5Sum< ::robobo_msgs::PlaySoundRequest> should match 
// service_traits::MD5Sum< ::robobo_msgs::PlaySound > 
template<>
struct MD5Sum< ::robobo_msgs::PlaySoundRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robobo_msgs::PlaySound >::value();
  }
  static const char* value(const ::robobo_msgs::PlaySoundRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robobo_msgs::PlaySoundRequest> should match 
// service_traits::DataType< ::robobo_msgs::PlaySound > 
template<>
struct DataType< ::robobo_msgs::PlaySoundRequest>
{
  static const char* value()
  {
    return DataType< ::robobo_msgs::PlaySound >::value();
  }
  static const char* value(const ::robobo_msgs::PlaySoundRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robobo_msgs::PlaySoundResponse> should match 
// service_traits::MD5Sum< ::robobo_msgs::PlaySound > 
template<>
struct MD5Sum< ::robobo_msgs::PlaySoundResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robobo_msgs::PlaySound >::value();
  }
  static const char* value(const ::robobo_msgs::PlaySoundResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robobo_msgs::PlaySoundResponse> should match 
// service_traits::DataType< ::robobo_msgs::PlaySound > 
template<>
struct DataType< ::robobo_msgs::PlaySoundResponse>
{
  static const char* value()
  {
    return DataType< ::robobo_msgs::PlaySound >::value();
  }
  static const char* value(const ::robobo_msgs::PlaySoundResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOBO_MSGS_MESSAGE_PLAYSOUND_H
