// Generated by gencpp from file robobo_msgs/ResetWheels.msg
// DO NOT EDIT!


#ifndef ROBOBO_MSGS_MESSAGE_RESETWHEELS_H
#define ROBOBO_MSGS_MESSAGE_RESETWHEELS_H

#include <ros/service_traits.h>


#include <robobo_msgs/ResetWheelsRequest.h>
#include <robobo_msgs/ResetWheelsResponse.h>


namespace robobo_msgs
{

struct ResetWheels
{

typedef ResetWheelsRequest Request;
typedef ResetWheelsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetWheels
} // namespace robobo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robobo_msgs::ResetWheels > {
  static const char* value()
  {
    return "b41202f44ec8802b6a66ae15859258a4";
  }

  static const char* value(const ::robobo_msgs::ResetWheels&) { return value(); }
};

template<>
struct DataType< ::robobo_msgs::ResetWheels > {
  static const char* value()
  {
    return "robobo_msgs/ResetWheels";
  }

  static const char* value(const ::robobo_msgs::ResetWheels&) { return value(); }
};


// service_traits::MD5Sum< ::robobo_msgs::ResetWheelsRequest> should match 
// service_traits::MD5Sum< ::robobo_msgs::ResetWheels > 
template<>
struct MD5Sum< ::robobo_msgs::ResetWheelsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robobo_msgs::ResetWheels >::value();
  }
  static const char* value(const ::robobo_msgs::ResetWheelsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robobo_msgs::ResetWheelsRequest> should match 
// service_traits::DataType< ::robobo_msgs::ResetWheels > 
template<>
struct DataType< ::robobo_msgs::ResetWheelsRequest>
{
  static const char* value()
  {
    return DataType< ::robobo_msgs::ResetWheels >::value();
  }
  static const char* value(const ::robobo_msgs::ResetWheelsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robobo_msgs::ResetWheelsResponse> should match 
// service_traits::MD5Sum< ::robobo_msgs::ResetWheels > 
template<>
struct MD5Sum< ::robobo_msgs::ResetWheelsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robobo_msgs::ResetWheels >::value();
  }
  static const char* value(const ::robobo_msgs::ResetWheelsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robobo_msgs::ResetWheelsResponse> should match 
// service_traits::DataType< ::robobo_msgs::ResetWheels > 
template<>
struct DataType< ::robobo_msgs::ResetWheelsResponse>
{
  static const char* value()
  {
    return DataType< ::robobo_msgs::ResetWheels >::value();
  }
  static const char* value(const ::robobo_msgs::ResetWheelsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOBO_MSGS_MESSAGE_RESETWHEELS_H
