// Generated by gencpp from file robobo_msgs/SetSensorFrequency.msg
// DO NOT EDIT!


#ifndef ROBOBO_MSGS_MESSAGE_SETSENSORFREQUENCY_H
#define ROBOBO_MSGS_MESSAGE_SETSENSORFREQUENCY_H

#include <ros/service_traits.h>


#include <robobo_msgs/SetSensorFrequencyRequest.h>
#include <robobo_msgs/SetSensorFrequencyResponse.h>


namespace robobo_msgs
{

struct SetSensorFrequency
{

typedef SetSensorFrequencyRequest Request;
typedef SetSensorFrequencyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSensorFrequency
} // namespace robobo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robobo_msgs::SetSensorFrequency > {
  static const char* value()
  {
    return "ea3a75b016df1ca9629d8a0e272b0401";
  }

  static const char* value(const ::robobo_msgs::SetSensorFrequency&) { return value(); }
};

template<>
struct DataType< ::robobo_msgs::SetSensorFrequency > {
  static const char* value()
  {
    return "robobo_msgs/SetSensorFrequency";
  }

  static const char* value(const ::robobo_msgs::SetSensorFrequency&) { return value(); }
};


// service_traits::MD5Sum< ::robobo_msgs::SetSensorFrequencyRequest> should match 
// service_traits::MD5Sum< ::robobo_msgs::SetSensorFrequency > 
template<>
struct MD5Sum< ::robobo_msgs::SetSensorFrequencyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robobo_msgs::SetSensorFrequency >::value();
  }
  static const char* value(const ::robobo_msgs::SetSensorFrequencyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robobo_msgs::SetSensorFrequencyRequest> should match 
// service_traits::DataType< ::robobo_msgs::SetSensorFrequency > 
template<>
struct DataType< ::robobo_msgs::SetSensorFrequencyRequest>
{
  static const char* value()
  {
    return DataType< ::robobo_msgs::SetSensorFrequency >::value();
  }
  static const char* value(const ::robobo_msgs::SetSensorFrequencyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robobo_msgs::SetSensorFrequencyResponse> should match 
// service_traits::MD5Sum< ::robobo_msgs::SetSensorFrequency > 
template<>
struct MD5Sum< ::robobo_msgs::SetSensorFrequencyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robobo_msgs::SetSensorFrequency >::value();
  }
  static const char* value(const ::robobo_msgs::SetSensorFrequencyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robobo_msgs::SetSensorFrequencyResponse> should match 
// service_traits::DataType< ::robobo_msgs::SetSensorFrequency > 
template<>
struct DataType< ::robobo_msgs::SetSensorFrequencyResponse>
{
  static const char* value()
  {
    return DataType< ::robobo_msgs::SetSensorFrequency >::value();
  }
  static const char* value(const ::robobo_msgs::SetSensorFrequencyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOBO_MSGS_MESSAGE_SETSENSORFREQUENCY_H
