// Generated by gencpp from file robobo_msgs/Talk.msg
// DO NOT EDIT!


#ifndef ROBOBO_MSGS_MESSAGE_TALK_H
#define ROBOBO_MSGS_MESSAGE_TALK_H

#include <ros/service_traits.h>


#include <robobo_msgs/TalkRequest.h>
#include <robobo_msgs/TalkResponse.h>


namespace robobo_msgs
{

struct Talk
{

typedef TalkRequest Request;
typedef TalkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Talk
} // namespace robobo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robobo_msgs::Talk > {
  static const char* value()
  {
    return "d8fdbf7e3675ec38cfc5f64bfa512f70";
  }

  static const char* value(const ::robobo_msgs::Talk&) { return value(); }
};

template<>
struct DataType< ::robobo_msgs::Talk > {
  static const char* value()
  {
    return "robobo_msgs/Talk";
  }

  static const char* value(const ::robobo_msgs::Talk&) { return value(); }
};


// service_traits::MD5Sum< ::robobo_msgs::TalkRequest> should match 
// service_traits::MD5Sum< ::robobo_msgs::Talk > 
template<>
struct MD5Sum< ::robobo_msgs::TalkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robobo_msgs::Talk >::value();
  }
  static const char* value(const ::robobo_msgs::TalkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robobo_msgs::TalkRequest> should match 
// service_traits::DataType< ::robobo_msgs::Talk > 
template<>
struct DataType< ::robobo_msgs::TalkRequest>
{
  static const char* value()
  {
    return DataType< ::robobo_msgs::Talk >::value();
  }
  static const char* value(const ::robobo_msgs::TalkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robobo_msgs::TalkResponse> should match 
// service_traits::MD5Sum< ::robobo_msgs::Talk > 
template<>
struct MD5Sum< ::robobo_msgs::TalkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robobo_msgs::Talk >::value();
  }
  static const char* value(const ::robobo_msgs::TalkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robobo_msgs::TalkResponse> should match 
// service_traits::DataType< ::robobo_msgs::Talk > 
template<>
struct DataType< ::robobo_msgs::TalkResponse>
{
  static const char* value()
  {
    return DataType< ::robobo_msgs::Talk >::value();
  }
  static const char* value(const ::robobo_msgs::TalkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOBO_MSGS_MESSAGE_TALK_H
